// <auto-generated />
using System;
using GenoDev.BusinessTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenoDev.BusinessTracker.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessTrackerDbContext))]
    [Migration("20260728195814_RecipeMaterialDescription")]
    partial class RecipeMaterialDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("business_tracker")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.FixedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("TotalCompanyAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("total_company_amount");

                    b.Property<double>("TotalPrivateAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("total_private_amount");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_fixed_assets");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasDatabaseName("ix_fixed_assets_ean")
                        .HasFilter("\"ean\" IS NOT NULL");

                    b.ToTable("fixed_assets", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.ToTable("materials", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.MaterialVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_code");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("TotalCompanyAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_company_amount");

                    b.Property<double>("TotalPrivateAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_private_amount");

                    b.Property<double>("TotalUsedAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_used_amount");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_material_variants");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasDatabaseName("ix_material_variants_ean")
                        .HasFilter("\"ean\" IS NOT NULL");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_material_variants_material_id");

                    b.ToTable("material_variants", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Carrier")
                        .HasColumnType("text")
                        .HasColumnName("carrier");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("order_identifier");

                    b.Property<string>("PaymentIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("payment_identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.OrderPackingMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PackingMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("packing_material_id");

                    b.HasKey("Id")
                        .HasName("pk_order_packing_materials");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_packing_materials_order_id");

                    b.HasIndex("PackingMaterialId")
                        .HasDatabaseName("ix_order_packing_materials_packing_material_id");

                    b.ToTable("order_packing_materials", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssignedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_amount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("UnitGrossPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_gross_price");

                    b.Property<decimal>("UnitNetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_net_price");

                    b.HasKey("Id")
                        .HasName("pk_order_products");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_products_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_products_product_id");

                    b.ToTable("order_products", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.PackingMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("TotalCompanyAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_company_amount");

                    b.Property<double>("TotalPrivateAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_private_amount");

                    b.Property<double>("TotalUsedAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_used_amount");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_packing_materials");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasDatabaseName("ix_packing_materials_ean")
                        .HasFilter("\"ean\" IS NOT NULL");

                    b.ToTable("packing_materials", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalSoldAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_sold_amount");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_products_identifier");

                    b.ToTable("products", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_recipes");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_recipes_product_id");

                    b.ToTable("product_recipes", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductRecipeMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("ProductRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_product_recipe_materials");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_product_recipe_materials_material_id");

                    b.HasIndex("ProductRecipeId")
                        .HasDatabaseName("ix_product_recipe_materials_product_recipe_id");

                    b.ToTable("product_recipe_materials", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("production_date");

                    b.HasKey("Id")
                        .HasName("pk_production");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_product_id");

                    b.ToTable("production", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductionMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_variant_id");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_id");

                    b.Property<double>("UsedAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("used_amount");

                    b.HasKey("Id")
                        .HasName("pk_production_materials");

                    b.HasIndex("MaterialVariantId")
                        .HasDatabaseName("ix_production_materials_material_variant_id");

                    b.HasIndex("ProductionId")
                        .HasDatabaseName("ix_production_materials_production_id");

                    b.ToTable("production_materials", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nip");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Nip")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_nip")
                        .HasFilter("\"nip\" IS NOT NULL");

                    b.ToTable("suppliers", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("text")
                        .HasColumnName("invoice_no");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("order_date");

                    b.Property<decimal>("ShippingGrossPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_gross_price");

                    b.Property<decimal>("ShippingNetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_net_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_supplies");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplies_supplier_id");

                    b.ToTable("supplies", "business_tracker");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.SupplyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FixedAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixed_asset_id");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<Guid>("MaterialSupplyId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_supply_id");

                    b.Property<Guid?>("MaterialVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_variant_id");

                    b.Property<Guid?>("PackingMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("packing_material_id");

                    b.Property<bool>("PrivateSupply")
                        .HasColumnType("boolean")
                        .HasColumnName("private_supply");

                    b.Property<decimal>("SetGrossPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("set_gross_price");

                    b.Property<decimal>("SetNetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("set_net_price");

                    b.Property<int>("SetsAmount")
                        .HasColumnType("integer")
                        .HasColumnName("sets_amount");

                    b.Property<double>("UnitsInSet")
                        .HasColumnType("double precision")
                        .HasColumnName("units_in_set");

                    b.HasKey("Id")
                        .HasName("pk_supply_items");

                    b.HasIndex("FixedAssetId")
                        .HasDatabaseName("ix_supply_items_fixed_asset_id");

                    b.HasIndex("MaterialSupplyId")
                        .HasDatabaseName("ix_supply_items_material_supply_id");

                    b.HasIndex("MaterialVariantId")
                        .HasDatabaseName("ix_supply_items_material_variant_id");

                    b.HasIndex("PackingMaterialId")
                        .HasDatabaseName("ix_supply_items_packing_material_id");

                    b.ToTable("supply_items", "business_tracker", t =>
                        {
                            t.HasCheckConstraint("CK_SupplyItem_XOR_Type", "(\"item_type\" = 1 AND \"material_variant_id\" IS NOT NULL AND \"packing_material_id\" IS NULL AND \"fixed_asset_id\" IS NULL) OR \r\n              (\"item_type\" = 2 AND \"material_variant_id\" IS NULL AND \"packing_material_id\" IS NOT NULL AND \"fixed_asset_id\" IS NULL) OR \r\n              (\"item_type\" = 3 AND \"material_variant_id\" IS NULL AND \"packing_material_id\" IS NULL AND \"fixed_asset_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.MaterialVariant", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Material", "Material")
                        .WithMany("MaterialVariants")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_variants_materials_material_id");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.OrderPackingMaterial", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Order", "Order")
                        .WithMany("OrderPackingMaterials")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_packing_materials_orders_order_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.PackingMaterial", "PackingMaterial")
                        .WithMany("OrderPackingMaterials")
                        .HasForeignKey("PackingMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_packing_materials_packing_materials_packing_material_");

                    b.Navigation("Order");

                    b.Navigation("PackingMaterial");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.OrderProduct", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_products_orders_order_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_products_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductRecipe", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("ProductRecipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_recipes_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductRecipeMaterial", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Material", "Material")
                        .WithMany("ProductRecipeMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_recipe_materials_materials_material_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.ProductRecipe", "ProductRecipe")
                        .WithMany("ProductRecipeMaterials")
                        .HasForeignKey("ProductRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_recipe_materials_product_recipes_product_recipe_id");

                    b.Navigation("Material");

                    b.Navigation("ProductRecipe");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Production", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("Productions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductionMaterial", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.MaterialVariant", "MaterialVariant")
                        .WithMany("ProductionMaterials")
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_materials_material_variants_material_variant_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Production", "Production")
                        .WithMany("ProductionMaterials")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_materials_productions_production_id");

                    b.Navigation("MaterialVariant");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supply", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplies_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.SupplyItem", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.FixedAsset", "FixedAsset")
                        .WithMany("SupplyItems")
                        .HasForeignKey("FixedAssetId")
                        .HasConstraintName("fk_supply_items_fixed_assets_fixed_asset_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Supply", "Supply")
                        .WithMany("SupplyItems")
                        .HasForeignKey("MaterialSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supply_items_supplies_material_supply_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.MaterialVariant", "MaterialVariant")
                        .WithMany("SupplyItems")
                        .HasForeignKey("MaterialVariantId")
                        .HasConstraintName("fk_supply_items_material_variants_material_variant_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.PackingMaterial", "PackingMaterial")
                        .WithMany("SupplyItems")
                        .HasForeignKey("PackingMaterialId")
                        .HasConstraintName("fk_supply_items_packing_materials_packing_material_id");

                    b.Navigation("FixedAsset");

                    b.Navigation("MaterialVariant");

                    b.Navigation("PackingMaterial");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.FixedAsset", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Material", b =>
                {
                    b.Navigation("MaterialVariants");

                    b.Navigation("ProductRecipeMaterials");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.MaterialVariant", b =>
                {
                    b.Navigation("ProductionMaterials");

                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderPackingMaterials");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.PackingMaterial", b =>
                {
                    b.Navigation("OrderPackingMaterials");

                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductRecipes");

                    b.Navigation("Productions");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductRecipe", b =>
                {
                    b.Navigation("ProductRecipeMaterials");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Production", b =>
                {
                    b.Navigation("ProductionMaterials");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supply", b =>
                {
                    b.Navigation("SupplyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
