using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GenoDev.BusinessTracker.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedIdsAndFilteredEanIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_products_ean_code",
                schema: "storage",
                table: "products");

            migrationBuilder.CreateIndex(
                name: "ix_products_ean_code",
                schema: "storage",
                table: "products",
                column: "ean_code",
                unique: true,
                filter: "\"ean_code\" IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_products_ean_code",
                schema: "storage",
                table: "products");

            migrationBuilder.CreateIndex(
                name: "ix_products_ean_code",
                schema: "storage",
                table: "products",
                column: "ean_code",
                unique: true);
        }
    }
}
