// <auto-generated />
using System;
using GenoDev.BusinessTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenoDev.BusinessTracker.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessTrackerDbContext))]
    [Migration("20260524201800_AutoGeneratedIdsAndFilteredEanIndex")]
    partial class AutoGeneratedIdsAndFilteredEanIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("business_tracker")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EanCode")
                        .HasColumnType("text")
                        .HasColumnName("ean_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("EanCode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_ean_code")
                        .HasFilter("\"ean_code\" IS NOT NULL");

                    b.ToTable("products", "storage");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductQuantityAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_product_quantity_adjustments");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_quantity_adjustments_product_id");

                    b.ToTable("product_quantity_adjustments", "storage");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Decription")
                        .HasColumnType("text")
                        .HasColumnName("decription");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalePriceGross")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price_gross");

                    b.Property<Guid>("SalesId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_id");

                    b.Property<Guid>("TaxRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_rate_id");

                    b.HasKey("Id")
                        .HasName("pk_product_sales");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_sales_product_id");

                    b.HasIndex("SalesId")
                        .HasDatabaseName("ix_product_sales_sales_id");

                    b.HasIndex("TaxRateId")
                        .HasDatabaseName("ix_product_sales_tax_rate_id");

                    b.ToTable("product_sales", "sales");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BuyPriceGross")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price_gross");

                    b.Property<decimal>("BuyPriceNet")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price_net");

                    b.Property<DateTimeOffset?>("BuyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buy_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<int>("SupplyStatus")
                        .HasColumnType("integer")
                        .HasColumnName("supply_status");

                    b.HasKey("Id")
                        .HasName("pk_product_supplies");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_supplies_product_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_product_supplies_supplier_id");

                    b.ToTable("product_supplies", "storage");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PaymentIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("payment_identifier");

                    b.Property<string>("SaleIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("sale_identifier");

                    b.Property<DateTimeOffset>("SaleTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_time");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.ToTable("sales", "sales");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.SalesCostsAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentValueGross")
                        .HasColumnType("numeric")
                        .HasColumnName("adjustment_value_gross");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("SalesId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_costs_adjustments");

                    b.HasIndex("SalesId")
                        .HasDatabaseName("ix_sales_costs_adjustments_sales_id");

                    b.ToTable("sales_costs_adjustments", "sales");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", "storage");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TaxRateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_rate_name");

                    b.Property<decimal>("TaxRateValue")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_rate_value");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id")
                        .HasName("pk_tax_rates");

                    b.ToTable("tax_rates", "sales");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductQuantityAdjustment", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("ProductQuantityAdjustments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_quantity_adjustments_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductSale", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sales_products_product_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Sale", "Sale")
                        .WithMany("ProductSales")
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sales_sales_sales_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany("ProductSales")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sales_tax_rates_tax_rate_id");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.ProductSupply", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Product", "Product")
                        .WithMany("ProductSupplies")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplies_products_product_id");

                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ProductSupplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplies_suppliers_supplier_id");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.SalesCostsAdjustment", b =>
                {
                    b.HasOne("GenoDev.BusinessTracker.Domain.Entities.Sale", "Sale")
                        .WithMany("SalesCostsAdjustments")
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_costs_adjustments_sales_sales_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductQuantityAdjustments");

                    b.Navigation("ProductSales");

                    b.Navigation("ProductSupplies");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Sale", b =>
                {
                    b.Navigation("ProductSales");

                    b.Navigation("SalesCostsAdjustments");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ProductSupplies");
                });

            modelBuilder.Entity("GenoDev.BusinessTracker.Domain.Entities.TaxRate", b =>
                {
                    b.Navigation("ProductSales");
                });
#pragma warning restore 612, 618
        }
    }
}
